version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  microservices.interview.identity.api:
    image: identity.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Identity/MicroServices.Interview.Identity.API/Dockerfile
    depends_on:
      - sql.data
      
  microservices.interview.personnel.api:
    image: personnel.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Personnel/MicroServices.Interview.Personnel.API/Dockerfile
    depends_on:
      - microservices.interview.identity.api
      - sql.data